local allWords = {
    { word = "crayon", scrambled = "rcayon", hint = "Used to color drawings?" },
    { word = "shower", scrambled = "osehrw", hint = "Used to clean your body?" },
    { word = "pan", scrambled = "apn", hint = "Used to fry food?" },
    { word = "mop", scrambled = "pom", hint = "Used to clean wet floors?" },
    { word = "broccoli", scrambled = "croocbil", hint = "Green vegetable with florets?" },
    { word = "computer", scrambled = "ctuorpem", hint = "Used for programming and internet?" },
    { word = "vacuum", scrambled = "mvuacu", hint = "Cleans carpets with suction?" },
    { word = "train", scrambled = "raint", hint = "Travels on tracks carrying passengers?" },
    { word = "potato", scrambled = "opotta", hint = "Can be made into fries?" },
    { word = "screwdriver", scrambled = "vrierdcerws", hint = "Tool for turning screws?" },
    { word = "microwave", scrambled = "vraeomwci", hint = "Heats food quickly?" },
    { word = "zebra", scrambled = "eabzr", hint = "Striped animal?" },
    { word = "banana", scrambled = "nbnaaa", hint = "Monkeys' favorite fruit?" },
    { word = "monkey", scrambled = "mnkeyo", hint = "Primate that climbs trees?" },
    { word = "kiwi", scrambled = "wiki", hint = "Small brown fruit with green inside?" },
    { word = "freezer", scrambled = "ezrrfee", hint = "Keeps food frozen?" },
    { word = "apple", scrambled = "plape", hint = "Fruit that keeps the doctor away?" },
    { word = "tomato", scrambled = "ttooma", hint = "Red fruit used in sauces?" },
    { word = "soap", scrambled = "paos", hint = "Used for washing hands?" },
    { word = "cookie", scrambled = "cokioe", hint = "Sweet baked treat often with chocolate chips?" },
    { word = "cup", scrambled = "puc", hint = "Used to drink liquids?" },
    { word = "notebook", scrambled = "okbeoont", hint = "Used to take school notes?" },
    { word = "pear", scrambled = "aepr", hint = "Fruit shaped like a teardrop?" },
    { word = "guitar", scrambled = "raiutg", hint = "Stringed instrument often used in music?" },
    { word = "clock", scrambled = "okclc", hint = "Tells you the time?" },
    { word = "lettuce", scrambled = "tetcleu", hint = "Leafy vegetable in salads?" },
    { word = "paint", scrambled = "apnti", hint = "Used to color walls or art?" },
    { word = "balloon", scrambled = "lobaonl", hint = "Inflatable object used for parties?" },
    { word = "egg", scrambled = "gge", hint = "Laid by chickens?" },
    { word = "game", scrambled = "egam", hint = "Played for fun or challenge?" },
    { word = "watermelon", scrambled = "mnwlaeroet", hint = "Big green fruit with red inside?" },
    { word = "trash", scrambled = "trsah", hint = "Where garbage goes?" },
    { word = "cucumber", scrambled = "ccrubume", hint = "Long green vegetable?" },
    { word = "drums", scrambled = "smdru", hint = "Percussion instrument?" },
    { word = "shirt", scrambled = "srhit", hint = "Worn on your upper body?" },
    { word = "mirror", scrambled = "rromri", hint = "Reflects your appearance?" },
    { word = "keyboard", scrambled = "kydrobae", hint = "Used to type on a computer?" },
    { word = "airplane", scrambled = "aalenrip", hint = "Flies people through the air?" },
    { word = "noodles", scrambled = "oesolnd", hint = "Long strands used in pasta?" },
    { word = "forest", scrambled = "roftse", hint = "Large area filled with trees?" },
    { word = "fridge", scrambled = "rgfedi", hint = "Keeps food cold?" },
    { word = "planet", scrambled = "tlapne", hint = "Earth is one of these in space?" },
    { word = "glasses", scrambled = "eslsgsa", hint = "Worn to help see better?" },
    { word = "rice", scrambled = "crei", hint = "Staple food in many countries?" },
    { word = "icecream", scrambled = "erecmiac", hint = "Cold sweet dessert?" },
    { word = "mountain", scrambled = "nintuamo", hint = "Very high natural landform?" },
    { word = "oven", scrambled = "veon", hint = "Used to bake food?" },
    { word = "tiger", scrambled = "tergi", hint = "Big cat with stripes?" },
    { word = "recycle", scrambled = "ceerylc", hint = "Used materials processed again?" },
    { word = "pencil", scrambled = "lpcnei", hint = "Used for writing or drawing?" },
    { word = "bed", scrambled = "ebd", hint = "You sleep on this?" },
    { word = "jeans", scrambled = "aensj", hint = "Common denim pants?" },
    { word = "spoon", scrambled = "nopso", hint = "Used to eat soup?" },
    { word = "toy", scrambled = "tyo", hint = "Object kids play with?" },
    { word = "bottle", scrambled = "tetlbo", hint = "Holds water or drinks?" },
    { word = "knife", scrambled = "knfie", hint = "Used to cut food?" },
    { word = "peach", scrambled = "aphce", hint = "Fuzzy fruit with a pit?" },
    { word = "fork", scrambled = "orfk", hint = "Used to eat solid food?" },
    { word = "corn", scrambled = "crno", hint = "Yellow kernels on a cob?" },
    { word = "book", scrambled = "okob", hint = "Collection of pages with stories or info?" },
    { word = "shoes", scrambled = "oeshs", hint = "Worn on your feet?" },
    { word = "plum", scrambled = "lump", hint = "Purple fruit with a pit?" },
    { word = "rainbow", scrambled = "iwornba", hint = "Colorful arc seen after rain?" },
    { word = "plate", scrambled = "atple", hint = "Food is served on this?" },
    { word = "phone", scrambled = "hneop", hint = "Used to make calls or send messages?" },
    { word = "hat", scrambled = "tha", hint = "Worn on the head?" },
    { word = "desert", scrambled = "eerstd", hint = "A dry, sandy region?" },
    { word = "soup", scrambled = "supo", hint = "Liquid meal served hot?" },
    { word = "onion", scrambled = "oonin", hint = "Makes you cry when cutting?" },
    { word = "cheese", scrambled = "eceehs", hint = "Made from milk and aged?" },
    { word = "towel", scrambled = "otlwe", hint = "Used to dry yourself?" },
    { word = "mouse", scrambled = "eumso", hint = "Computer pointing device?" },
    { word = "bread", scrambled = "badre", hint = "Basic food made from flour?" },
    { word = "blanket", scrambled = "nekbatl", hint = "Keeps you warm while sleeping?" },
    { word = "elephant", scrambled = "etlpneha", hint = "The largest land animal?" },
    { word = "school", scrambled = "oshocl", hint = "Place where students learn?" },
    { word = "broom", scrambled = "oborm", hint = "Used to sweep floors?" },
    { word = "rocket", scrambled = "cetkro", hint = "Used to travel into space?" },
    { word = "brush", scrambled = "ubshr", hint = "Tool for painting or grooming?" },
    { word = "television", scrambled = "iliesnetov", hint = "Used to watch shows or news?" },
    { word = "soccer", scrambled = "secorc", hint = "Kicking a ball into a goal is part of this game?" },
    { word = "sink", scrambled = "nisk", hint = "Used for washing dishes?" },
    { word = "lamp", scrambled = "amlp", hint = "Used to light up a room?" },
    { word = "pillow", scrambled = "pliwlo", hint = "Rest your head on this in bed?" },
    { word = "robot", scrambled = "borto", hint = "A machine that can do tasks?" },
    { word = "window", scrambled = "iodnww", hint = "You look outside through this?" },
    { word = "grape", scrambled = "geapr", hint = "Small round fruit in bunches?" },
    { word = "pumpkin", scrambled = "mppiunk", hint = "Orange fruit used in Halloween?" },
    { word = "door", scrambled = "rdoo", hint = "You open and close this to enter rooms?" },
    { word = "camera", scrambled = "ramace", hint = "Used to take photographs?" },
    { word = "stove", scrambled = "soetv", hint = "Used for cooking on pots?" },
    { word = "flower", scrambled = "flwroe", hint = "Blooms and smells good?" },
    { word = "butter", scrambled = "tbetru", hint = "Spread made from cream?" },
    { word = "toilet", scrambled = "loeitt", hint = "Used in the bathroom?" },
    { word = "hammer", scrambled = "mehram", hint = "Tool for hitting nails?" },
    { word = "laptop", scrambled = "plptao", hint = "Portable computer?" },
    { word = "bridge", scrambled = "edirgb", hint = "Structure that connects two places?" },
    { word = "jacket", scrambled = "cjetak", hint = "Worn to keep warm?" },
    { word = "lion", scrambled = "lnio", hint = "King of the jungle?" },
    { word = "carrot", scrambled = "rtoacr", hint = "Orange root vegetable?" },
}